import "./styles.scss";
import "./scripts";
import "./layout/index.pug";
import "./components/header/header.pug";
import "./components/features/features.pug";
import "./components/services/services.pug";
import "./components/footer/footer.pug";
import "./components/vacancies/vacancies.pug";
import "./components/students-feedback/students-feedback.pug";
